// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLjsBhxGpWSKPDcQyCuwkQJEkb9C3Vy1E',
    appId: '1:332563196298:web:983c7816443a57933b4073',
    messagingSenderId: '332563196298',
    projectId: 'fireprojek',
    authDomain: 'fireprojek.firebaseapp.com',
    storageBucket: 'fireprojek.appspot.com',
    measurementId: 'G-4YL8E6M944',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCU4S3EdwSvWL5gVNKcwWDqxB6TLh6Bek',
    appId: '1:332563196298:android:1382bbc7ff784d4a3b4073',
    messagingSenderId: '332563196298',
    projectId: 'fireprojek',
    storageBucket: 'fireprojek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhyjgZnd8coCc48o5TesNhq85w8PwZ04',
    appId: '1:332563196298:ios:3c8e6e23a75cf8b33b4073',
    messagingSenderId: '332563196298',
    projectId: 'fireprojek',
    storageBucket: 'fireprojek.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxhyjgZnd8coCc48o5TesNhq85w8PwZ04',
    appId: '1:332563196298:ios:3c8e6e23a75cf8b33b4073',
    messagingSenderId: '332563196298',
    projectId: 'fireprojek',
    storageBucket: 'fireprojek.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLjsBhxGpWSKPDcQyCuwkQJEkb9C3Vy1E',
    appId: '1:332563196298:web:f393882e7a02460b3b4073',
    messagingSenderId: '332563196298',
    projectId: 'fireprojek',
    authDomain: 'fireprojek.firebaseapp.com',
    storageBucket: 'fireprojek.appspot.com',
    measurementId: 'G-554CDLJVTT',
  );
}
